# Generated by Django 4.2.3 on 2023-07-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=30)),
                ('year', models.DateField()),
                ('cost', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
